import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("the interface follows the black red and white design system", async () => {
  const [css, app, html] = await Promise.all([
    readFile(new URL("../styles.css", import.meta.url), "utf8"),
    readFile(new URL("../src/app.js", import.meta.url), "utf8"),
    readFile(new URL("../index.html", import.meta.url), "utf8"),
  ]);

  assert.match(css, /--black:\s*#000000/);
  assert.match(css, /--red:\s*#db0814/);
  assert.match(css, /--white:\s*#ffffff/);
  assert.match(css, /--font-display:[^;]*UnifrakturCook/);
  assert.match(css, /--font-ui:[^;]*Noto Serif JP/);
  assert.match(css, /\.top-bar[^}]*border-bottom:\s*4px solid var\(--white\)/s);
  assert.match(css, /button\s*\{[^}]*border:\s*3px solid var\(--white\)/s);
  assert.doesNotMatch(css, /box-shadow|text-shadow/);
  assert.match(app, /unit\.team === "ally" \? "#ffffff" : "#db0814"/);
  assert.match(app, /from "\.\/simulation\.js\?v=10"/);
  assert.match(html, /name="theme-color" content="#000000"/);
  assert.match(html, /<title>EISENHERZ<\/title>/);
  assert.match(html, /<link rel="icon" href="\.\/assets\/icon\/icon\.ico" sizes="any">/);
  assert.match(html, /href="\.\/styles\.css\?v=29"/);
  assert.match(html, /src="\.\/src\/app\.js\?v=67"/);
  assert.match(html, /<h1>DEMO<\/h1>/);
  assert.match(html, /<p class="eyebrow">EISENHERZ<\/p>/);
  assert.match(html, /id="loading" class="loading" role="status" aria-live="polite"/);
  assert.match(html, /id="title-screen" class="title-screen front-screen"/);
  assert.match(html, /id="title-new-game"[^>]*data-difficulty="easy"[\s\S]*easy\.webp/);
  assert.match(html, /src="\.\/assets\/title\/normal\.webp"/);
  assert.match(html, /src="\.\/assets\/title\/hard\.webp"/);
  assert.match(html, /src="\.\/assets\/title\/continue\.webp"/);
  assert.match(html, /src="\.\/assets\/title\/tool\.webp"/);
  assert.match(html, /id="scenario-screen" class="scenario-screen front-screen"/);
  assert.match(html, /id="scenario-screen-title" class="visually-hidden">シナリオ選択<\/h2>/);
  assert.match(html, /id="scenario-list" aria-label="シナリオ一覧"/);
  assert.match(html, /<article id="scenario-detail">/);
  assert.match(html, /<h3 id="scenario-title"><\/h3>/);
  assert.match(html, /id="scenario-start"[^>]*aria-label="シナリオを開始"[^>]*><\/button>/);
  assert.doesNotMatch(html, /scenario-back|Eisenherz\.|N° I — OPERATIONS|OPERATION ARCHIVE/);
  assert.match(html, /class="loading-kicker">EISENHERZ<\/p>/);
  assert.match(html, /<strong>LOADING<\/strong>/);
  assert.match(html, /id="loading-message">INITIALIZING\.\.\.<\/span>/);
  assert.match(html, /id="ally-count">1<\/b>\s*<span id="ally-label">OWN<\/span>/);
  assert.match(html, /id="enemy-count">1<\/b>\s*<span id="enemy-label">NEUTRAL<\/span>/);
  assert.match(html, /id="toggle-pause"[^>]*>END TURN<\/button>/);
  assert.match(html, /id="header-help"[^>]*aria-label="操作方法を開く"[^>]*>HELP<\/button>/);
  assert.doesNotMatch(html, /id="restart"/);
  assert.match(html, /class="commander-panel hud-panel"/);
  assert.match(html, /id="strategy-panel" class="strategy-panel hud-panel"/);
  assert.doesNotMatch(html, /id="strategy-invade"[^>]*>INVADE<\/button>/);
  assert.doesNotMatch(html, /id="strategy-clear"[^>]*>CLEAR<\/button>/);
  assert.match(html, /id="strategy-selected-forces" class="strategy-selected-forces"[^>]*hidden/);
  assert.match(html, /id="invasion-dialog"[\s\S]*role="dialog"/);
  assert.match(html, /id="confirm-invasion"[^>]*>出撃<\/button>/);
  assert.match(html, /id="cancel-invasion"[^>]*>キャンセル<\/button>/);
  assert.match(html, /id="end-turn-title">ターンを終了しますか？<\/h2>/);
  assert.match(html, /id="end-turn-description"[^>]*>ターンを終了すると、残っている行動は実行できなくなります。<\/p>/);
  assert.match(html, /id="confirm-end-turn"[^>]*>ターンを終了<\/button>/);
  assert.match(html, /id="cancel-end-turn"[^>]*>キャンセル<\/button>/);
  assert.match(html, /id="battle-briefing"[\s\S]*role="dialog"/);
  assert.match(html, /id="battle-briefing-title">戦闘準備完了<\/h2>/);
  assert.match(html, /id="begin-battle"[^>]*>戦闘開始<\/button>/);
  assert.match(html, /id="legend-help">拠点クリック: 選択 \/ 画面端: スクロール<\/span>/);
  assert.match(html, /id="zoom-level">54%<\/span>/);
  assert.match(html, /class="unit-status-panel hud-panel"/);
  assert.match(html, /id="formation-panel"/);
  assert.match(html, /id="panel-selection-box"[^>]*hidden/);
  assert.match(html, /data-select-scope="all">ALL UNITS<\/button>/);
  assert.match(html, /id="set-control-hold"[^>]*tabindex="-1"[^>]*>HOLD<\/button>/);
  assert.match(html, /id="set-control-auto"[^>]*tabindex="-1"[^>]*>AUTO<\/button>/);
  assert.match(html, /id="set-formation-line"[^>]*tabindex="-1"[^>]*>LINE<\/button>/);
  assert.match(html, /id="set-formation-square"[^>]*tabindex="-1"[^>]*>SQUARE<\/button>/);
  assert.match(html, /id="set-formation-dense"[^>]*tabindex="-1"[^>]*>DENSE<\/button>/);
  assert.match(html, /data-select-role="frontline">FRONTLINE<\/button>/);
  assert.match(html, /data-select-role="rearGuard">REAR GUARD<\/button>/);
  assert.match(html, /id="selection-box"[^>]*hidden/);
  assert.match(html, /class="commander-name">ELISE<\/strong>/);
  assert.match(html, /src="\.\/assets\/character\/char1\.webp"/);
  assert.match(html, /id="panel-unit-count"/);
  assert.match(html, /id="panel-unit-count">24<\/span>\s*\/ 24/);
  assert.match(html, /id="panel-strength"/);
  assert.match(html, /id="panel-status"/);
  assert.match(html, /id="battle-result"[^>]*hidden/);
  assert.match(html, /id="result-title"/);
  assert.match(html, /id="result-restart"[^>]*>RESTART BATTLE<\/button>/);
  assert.match(html, /id="screen-transition" class="screen-transition"[^>]*hidden/);
  assert.match(html, /id="start-screen"/);
  assert.match(html, /id="start-title">EISENHERZ<\/h2>/);
  assert.match(html, /id="start-battle"[^>]*>START BATTLE<\/button>/);
  assert.match(html, /id="show-controls"[^>]*>CONTROLS<\/button>/);
  assert.match(html, /id="controls-dialog"[\s\S]*role="dialog"/);
  assert.match(html, /id="start-screen"[\s\S]*id="show-controls"[\s\S]*<\/section>\s*<section\s+id="controls-dialog"/);
  assert.match(html, /id="controls-list"/);
  assert.match(html, /id="close-controls"[^>]*>CLOSE<\/button>/);
  assert.doesNotMatch(html, /CLICK \/ ENTER \/ SPACE TO START/);
  assert.doesNotMatch(html, /class="start-controls"/);
  assert.doesNotMatch(app, /startScreen\.addEventListener\("pointerup"/);
  assert.match(css, /button\.is-active\s*\{[^}]*background:\s*var\(--white\)/s);
  assert.match(css, /--cursor-default:\s*url\("\.\/assets\/icon\/mouse\.png"\) 0 0, auto;/);
  assert.match(css, /\*\s*\{[^}]*cursor:\s*var\(--cursor-default\)/s);
  assert.doesNotMatch(css, /cursor:\s*pointer/);
  assert.match(css, /\.battle-result,\s*\.invasion-dialog,\s*\.battle-briefing\s*\{[^}]*border:\s*4px solid var\(--white\)/s);
  assert.match(css, /#result-restart\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(css, /body\s*\{[^}]*position:\s*fixed;[^}]*inset:\s*0;/s);
  assert.match(css, /\.game-shell\s*\{[^}]*height:\s*var\(--app-height, 100dvh\);[^}]*overflow:\s*hidden/s);
  assert.match(css, /\.loading\s*\{[^}]*position:\s*fixed;[^}]*z-index:\s*30;[^}]*background:\s*var\(--black\)/s);
  assert.match(css, /\.front-screen\s*\{[^}]*position:\s*fixed;[^}]*z-index:\s*25/s);
  assert.match(css, /\.title-stage\s*\{[^}]*title\.webp/s);
  assert.match(css, /\.scenario-screen\s*\{[^}]*background:\s*var\(--black\)/s);
  assert.doesNotMatch(css, /scenario-(?:corner|map-preview|stage|start|simple|brand|context|back)/);
  assert.match(css, /\.loading-card\s*\{[^}]*border:\s*4px solid var\(--white\)/s);
  assert.match(css, /\.loading i\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(css, /\.start-screen\s*\{[^}]*position:\s*fixed;[^}]*background:\s*var\(--black\)/s);
  assert.match(css, /\.screen-transition\s*\{[^}]*position:\s*fixed;[^}]*z-index:\s*29;[^}]*background:\s*var\(--black\)/s);
  assert.match(css, /\.screen-transition\.is-visible\s*\{[^}]*opacity:\s*1/s);
  assert.match(css, /#start-battle\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(css, /\.controls-dialog\s*\{[^}]*border:\s*4px solid var\(--white\)/s);
  assert.match(app, /const CONTROL_GUIDES = Object\.freeze\(\{[\s\S]*?STRATEGY ORDERS[\s\S]*?BATTLE ORDERS/s);
  assert.match(app, /headerHelpButton\.addEventListener\("click", showHeaderControls\)/);
  assert.match(app, /renderControlsGuide\(state\.mode === "strategy" \? "strategy" : "battle"\)/);
  assert.match(css, /\.commander-panel\s*\{[^}]*width:\s*min\(360px, calc\(100vw - 28px\)\);[^}]*border:\s*3px solid var\(--white\)/s);
  assert.match(css, /\.strategy-panel\s*\{[^}]*width:\s*min\(360px, calc\(100vw - 28px\)\);[^}]*border:\s*3px solid var\(--white\)/s);
  assert.match(css, /\.strategy-selected-forces\s*\{[^}]*border-bottom:\s*3px solid var\(--white\)/s);
  assert.match(css, /\.strategy-spot-panel\.is-drop-hover\s*\{[^}]*background:\s*var\(--white\)/s);
  assert.match(css, /\.strategy-drag-ghost\s*\{[^}]*position:\s*fixed;[^}]*pointer-events:\s*none/s);
  assert.match(css, /\.strategy-drag-ghost\.is-valid\s*\{[^}]*border-color:\s*var\(--white\)/s);
  assert.match(css, /#begin-battle\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(css, /#confirm-invasion\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(app, /const INVASION_DIALOG_FRONT_Z_INDEX = 70/);
  assert.match(app, /function showInvasionDialog\(\) \{[\s\S]*?bringHudPanelToFront\(invasionDialog\);[\s\S]*?invasionDialog\.hidden = false;/s);
  assert.match(css, /\.commander-summary\s*\{[^}]*grid-template-columns:\s*96px minmax\(0, 1fr\);[^}]*min-height:\s*96px/s);
  assert.match(css, /\.commander-portrait\s*\{[^}]*width:\s*96px;[^}]*height:\s*96px;[^}]*aspect-ratio:\s*1 \/ 1/s);
  assert.match(css, /\.force-status div\s*\{[^}]*display:\s*grid;[^}]*border:\s*2px solid var\(--white\)/s);
  assert.match(css, /\.panel-status\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*auto minmax\(0, 1fr\);[^}]*border-bottom:\s*3px solid var\(--white\)/s);
  assert.doesNotMatch(css, /cursor:\s*move/);
  assert.doesNotMatch(css, /cursor:\s*grabbing/);
  assert.match(css, /\.command-mode-buttons\s*\{[^}]*grid-template-columns:\s*1fr 1fr/s);
  assert.match(css, /\.formation-mode-buttons\s*\{[^}]*grid-template-columns:\s*repeat\(3, 1fr\)/s);
  assert.match(css, /\.unit-status-panel\s*\{[^}]*top:\s*14px;[^}]*right:\s*14px;[^}]*width:\s*min\(390px, calc\(100vw - 28px\)\)/s);
  assert.match(css, /\.faction-heading img\s*\{[^}]*display:\s*block;[^}]*aspect-ratio:\s*1 \/ 1;[^}]*border-right:\s*3px solid var\(--white\);[^}]*border-bottom:\s*3px solid var\(--white\)/s);
  assert.match(css, /\.faction-heading > div\s*\{[^}]*align-self:\s*stretch;[^}]*border-bottom:\s*3px solid var\(--white\)/s);
  assert.match(css, /\.formation-units\s*\{[^}]*overflow-x:\s*auto/s);
  assert.match(css, /\.unit-card\.is-selected\s*\{[^}]*border-color:\s*var\(--red\)/s);
  assert.match(css, /\.selection-box\s*\{[^}]*border:\s*2px solid var\(--white\)/s);
  assert.match(css, /\.panel-selection-box\s*\{[^}]*border:\s*2px solid var\(--red\)/s);
  assert.match(css, /\.battle-status\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) 148px minmax\(0, 1fr\)/s);
  assert.match(css, /\.battle-status\s*\{[^}]*width:\s*372px;[^}]*min-width:\s*372px;[^}]*max-width:\s*372px/s);
  assert.match(css, /\.battle-status\[hidden\]\s*\{\s*display:\s*none;/);
  assert.match(css, /\.controls button\s*\{[^}]*min-width:\s*72px/s);
  assert.match(css, /#battle-message\s*\{[^}]*width:\s*100%;[^}]*max-width:\s*148px/s);
  assert.match(app, /battleStatus\.hidden = screen === FLOW_SCREEN\.FACTION;/);
  assert.match(app, /\["Enter", "Space"\]\.includes\(event\.code\)/);
  assert.match(app, /if \(!controlsDialog\.hidden\)/);
  assert.match(app, /event\.code === "Escape"/);
  assert.match(app, /window\.visualViewport\?\.addEventListener\("resize", syncViewportSize\)/);
  assert.match(app, /const loadingMessage = document\.getElementById\("loading-message"\)/);
  assert.match(app, /loadingMessage\.textContent = `起動エラー: \$\{error\.message\}`/);
  assert.match(app, /window\.addEventListener\("resize", syncViewportSize\)/);
  assert.match(app, /function syncViewportSize\(\)/);
  assert.match(app, /document\.documentElement\.style\.setProperty\("--app-height"/);
  assert.match(app, /window\.addEventListener\("click", blurClickedButton\)/);
  assert.match(app, /function blurClickedButton\(event\)/);
  assert.match(app, /event\.target\.closest\?\.\("button"\)\?\.blur\(\)/);
  assert.match(app, /event\.code === "Space"[\s\S]*?event\.preventDefault\(\)/);
  assert.doesNotMatch(app, /event\.target\.matches\?\.\("input, textarea, select, button/);
  assert.match(app, /function buildFormationPanel\(\)/);
  assert.match(app, /function startMapSelection\(event\)/);
  assert.match(app, /function startPanelSelection\(event\)/);
  assert.match(app, /function startExternalPanelSelection\(event\)/);
  assert.match(app, /function startHudPanelDrag\(event\)/);
  assert.match(app, /const allButton = event\.target\.closest\("\[data-strategy-select-scope='all'\]"\)/);
  assert.match(app, /type: "all",\s*spotId: spot\.id,\s*unitIds: ids/s);
  assert.match(app, /function createStrategyDragGhost\(units\)/);
  assert.match(app, /if \(event\.target\.closest\?\.\("button"\)\) return;/);
  assert.match(app, /function placeHudPanel\(panel, clientLeft, clientTop\)/);
  assert.match(app, /function stopPanelDragFromControlButton\(event\)/);
  assert.match(app, /function setFormationStyle\(style\)/);
  assert.match(app, /function syncFormationStyleButton\(\)/);
  assert.match(app, /function drawActiveMoveGhosts\(\)/);
  assert.match(app, /drawMoveGhost\(destination\.x, destination\.y, destination\.role, "committed"\)/);
  assert.match(app, /ctx\.setLineDash\(isCommitted \? \[10, 8\] : \[\]\)/);
  assert.match(app, /ctx\.globalAlpha = isCommitted \? 0\.62 : 1/);
  assert.match(app, /function startCommandDrag\(event\)/);
  assert.match(app, /import \{\s*buildFormationDestinations,\s*\} from "\.\/formation\.js"/s);
  assert.match(app, /function selectedFormationDestinations\(centerX, centerY, angle\)/);
  assert.match(app, /return buildFormationDestinations\(\{\s*centerX,\s*centerY,\s*angle,\s*units,\s*style: state\.formationStyle,/s);
  assert.match(app, /canvas\.addEventListener\("contextmenu", event => event\.preventDefault\(\)\)/);
  assert.match(app, /window\.addEventListener\("contextmenu", handleScreenBack, \{ capture: true \}\)/);
  assert.match(app, /function handleStrategySpotPanelContextMenu\(event\) \{[\s\S]*?selectStrategyAttackTarget\(spot\);[\s\S]*?closeStrategySpotPanel\(panel\.dataset\.spotId\);/);
  assert.match(app, /function closeStrategySpotPanel\(spotId\) \{[\s\S]*?const closesTargetPanel = state\.strategy\.selectedTargetId === spotId;[\s\S]*?if \(closesTargetPanel\) \{/);
  assert.match(app, /function syncStrategySortiePanel\(\) \{[\s\S]*?renderStrategySortiePanel\(panel, target\);\s*\}/);
  assert.match(app, /function selectStrategyAttackTarget\(spot\) \{[\s\S]*?syncStrategySortiePanel\(\);[\s\S]*?placeStrategySortiePanel\(state\.strategySortiePanel, targetPanel\);/);
  assert.match(app, /function startStrategySelection\(event\) \{[\s\S]*?if \(event\.button === 2\) event\.preventDefault\(\);[\s\S]*?const spot = strategySpotAt/s);
  assert.match(app, /function handleScreenBack\(event\) \{\s*event\.preventDefault\(\);\s*if \(!\[FLOW_SCREEN\.SCENARIO, FLOW_SCREEN\.FACTION\]\.includes\(state\.flow\.screen\)\) return;/);
  assert.match(app, /!\[FLOW_SCREEN\.SCENARIO, FLOW_SCREEN\.FACTION\]\.includes\(state\.flow\.screen\)/);
  assert.doesNotMatch(app, /!\[FLOW_SCREEN\.SCENARIO, FLOW_SCREEN\.FACTION, FLOW_SCREEN\.STRATEGY\]\.includes\(state\.flow\.screen\)/);
  assert.match(app, /handleScreenBack\(event\)[\s\S]*?handleHeaderBack\(\);/);
  assert.match(app, /state\.flow\.screen === FLOW_SCREEN\.SCENARIO\) \{\s*runScreenTransition\(showTitleScreen\);/s);
  assert.match(app, /headerBackButton\.hidden = screen !== FLOW_SCREEN\.STRATEGY/);
  assert.match(app, /pauseButton\.hidden = screen === FLOW_SCREEN\.FACTION/);
  assert.match(app, /runScreenTransition\(returnToScenarioScreen\)/);
  assert.match(app, /function returnToScenarioScreen\(\) \{\s*resetScenarioSessionState\(\);\s*updateGameFlow\(FLOW_EVENT\.RETURN_SCENARIOS\);\s*\}/s);
  assert.match(app, /function resetScenarioSessionState\(\) \{[\s\S]*?state\.selectedFactionId = null;[\s\S]*?state\.strategyCleared = false;[\s\S]*?resetStrategyState\(\);[\s\S]*?resetBattle\(\{ waitForStart: true \}\);/s);
  assert.match(app, /function resetStrategyState\(\) \{[\s\S]*?state\.strategy = createStrategyState\(state\.strategyData, state\.selectedFactionId \?\? "deutschland"\)/s);
  assert.match(app, /function enterStrategyMode\(\) \{\s*closeStrategyTransientUi\(\);/s);
  assert.match(app, /function transitionToStrategyMode\(\) \{[\s\S]*?clearStrategySelection\(\);[\s\S]*?enterStrategyMode\(\);/s);
  assert.match(app, /function closeStrategyTransientUi\(\) \{[\s\S]*?state\.strategy\.openSpotPanels\.clear\(\)/s);
  assert.doesNotMatch(app, /setAllyControlMode\(state\.battle, "hold"\)/);
  assert.match(app, /issueMoveOrder\(state\.battle, destinations\)/);
  assert.match(app, /function unitCardsInClientBounds\(bounds\)/);
  assert.match(app, /function alliedUnitsInScreenBounds\(bounds\)/);
  assert.match(app, /function toggleSelectionBy\(predicate, additive = false\)/);
  assert.match(app, /function toggleUnitSelection\(ids, additive = false\)/);
  assert.match(app, /if \(!additive && isEntireGroupSelected\(nextIds\)\)/);
  assert.match(app, /ctx\.rotate\(Math\.atan2\(dy, dx\) \+ Math\.PI\)/);
  assert.match(app, /if \(!state\.started\) \{\s*if \(event\.code === "Enter"\) \{\s*event\.preventDefault\(\);\s*startBattle\(\);/s);
  assert.match(app, /if \(state\.mode === "battle" && state\.started && !state\.paused\) updateBattle/);
  assert.match(app, /!isStrategyMapMode\(\) &&\s*\(!state\.started \|\| state\.battle\?\.winner\)/);
  assert.doesNotMatch(app, /!isStrategyMapMode\(\) &&\s*\(!state\.started \|\| state\.paused/);
  assert.match(app, /pauseButton\.textContent = state\.paused \? "RESUME" : "PAUSE"/);
  assert.match(app, /STRATEGY_ASSET_URLS/);
  assert.match(app, /function enterStrategyMode\(\)/);
  assert.match(app, /function showTitleScreen\(\)/);
  assert.match(app, /function openScenarioScreen\(difficulty = "easy"\)/);
  assert.match(app, /function renderScenarioSelection\(\)/);
  assert.match(app, /function selectScenario\(scenarioId\)/);
  assert.match(
    app,
    /async function runScenarioLoadingTransition\(\)[\s\S]*?screenTransition\.classList\.add\("is-visible"\);[\s\S]*?await delay\(SCREEN_TRANSITION_FADE_MS\);[\s\S]*?updateGameFlow\(FLOW_EVENT\.CHOOSE_FACTION/s
  );
  assert.match(app, /function startSelectedScenario\(\)/);
  assert.match(app, /function drawStrategyMap\(\)/);
  assert.match(app, /function trackStrategyHover\(event\)/);
  assert.match(app, /function syncStrategyHover\(\)/);
  assert.match(app, /STRATEGY_FACTION_MARKER_COLORS/);
  assert.match(app, /function hoveredStrategyFactionId\(\)/);
  assert.match(app, /function strategyFactionMarkerColor\(factionId\)/);
  assert.doesNotMatch(app, /strategyHoverScales/);
  assert.match(app, /function invadeSelectedSpot\(\)/);
  assert.match(app, /function endStrategyTurn\(\) \{[\s\S]*?state\.strategy\.spots\.every\(spot => spot\.owner === "player"\)[\s\S]*?showStrategyClearResult\(\);[\s\S]*?return;/s);
  assert.match(app, /function showStrategyClearResult\(\) \{[\s\S]*?resultTitle\.textContent = "SCENARIO CLEAR"[\s\S]*?battleResult\.hidden = false;/s);
  assert.match(app, /const STRATEGY_CAMERA_SCALE = 1\.8;/);
  assert.match(app, /const STRATEGY_EDGE_SPEED = 780;/);
  assert.match(app, /const SCREEN_TRANSITION_HOLD_MS = 520;/);
  assert.match(app, /function runScreenTransition\(action, options = \{\}\)/);
  assert.match(app, /function createStrategyCamera\(\) \{[\s\S]*?scale:\s*STRATEGY_CAMERA_SCALE/s);
  assert.match(app, /isStrategyMapMode\(\) \? STRATEGY_EDGE_SPEED : undefined/);
  assert.match(app, /function zoomWithWheel\(event\) \{\s*if \(isStrategyMapMode\(\)\) \{[\s\S]*?event\.preventDefault\(\);[\s\S]*?return;/s);
  assert.match(app, /function initialCameraScale\(\) \{\s*return CAMERA_LIMITS\.minScale;/s);
});
