import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("the interface follows the black red and white design system", async () => {
  const [css, app, html] = await Promise.all([
    readFile(new URL("../styles.css", import.meta.url), "utf8"),
    readFile(new URL("../src/app.js", import.meta.url), "utf8"),
    readFile(new URL("../index.html", import.meta.url), "utf8"),
  ]);

  assert.match(css, /--black:\s*#000000/);
  assert.match(css, /--red:\s*#db0814/);
  assert.match(css, /--white:\s*#ffffff/);
  assert.match(css, /--font-display:[^;]*UnifrakturCook/);
  assert.match(css, /--font-ui:[^;]*Noto Serif JP/);
  assert.match(css, /\.top-bar[^}]*border-bottom:\s*4px solid var\(--white\)/s);
  assert.match(css, /button\s*\{[^}]*border:\s*3px solid var\(--white\)/s);
  assert.doesNotMatch(css, /box-shadow|text-shadow/);
  assert.match(app, /unit\.team === "ally" \? "#ffffff" : "#db0814"/);
  assert.match(app, /from "\.\/simulation\.js\?v=9"/);
  assert.match(html, /name="theme-color" content="#000000"/);
  assert.match(html, /<title>EISENHERZ<\/title>/);
  assert.match(html, /<link rel="icon" href="\.\/assets\/icon\/icon\.ico" sizes="any">/);
  assert.match(html, /href="\.\/styles\.css\?v=10"/);
  assert.match(html, /src="\.\/src\/app\.js\?v=13"/);
  assert.match(html, /<h1>DEMO<\/h1>/);
  assert.match(html, /<p class="eyebrow">EISENHERZ<\/p>/);
  assert.match(html, /id="loading" class="loading" role="status" aria-live="polite"/);
  assert.match(html, /class="loading-kicker">EISENHERZ<\/p>/);
  assert.match(html, /<strong>LOADING<\/strong>/);
  assert.match(html, /id="loading-message">戦場データを構築しています<\/span>/);
  assert.match(html, /id="ally-count">24<\/b>\s*ALLIES<\/span>/);
  assert.match(html, /id="enemy-count">24<\/b>\s*ENEMIES<\/span>/);
  assert.match(html, /id="toggle-pause"[^>]*>PAUSE<\/button>/);
  assert.match(html, /id="restart"[^>]*>RESTART<\/button>/);
  assert.match(html, /class="commander-panel hud-panel"/);
  assert.match(html, /class="unit-status-panel hud-panel"/);
  assert.match(html, /id="formation-panel"/);
  assert.match(html, /id="panel-selection-box"[^>]*hidden/);
  assert.match(html, /data-select-scope="all">ALL UNITS<\/button>/);
  assert.match(html, /id="set-control-hold"[^>]*tabindex="-1"[^>]*>HOLD<\/button>/);
  assert.match(html, /id="set-control-auto"[^>]*tabindex="-1"[^>]*>AUTO<\/button>/);
  assert.match(html, /id="set-formation-line"[^>]*tabindex="-1"[^>]*>LINE<\/button>/);
  assert.match(html, /id="set-formation-square"[^>]*tabindex="-1"[^>]*>SQUARE<\/button>/);
  assert.match(html, /data-select-role="frontline">FRONTLINE<\/button>/);
  assert.match(html, /data-select-role="rearGuard">REAR GUARD<\/button>/);
  assert.match(html, /id="selection-box"[^>]*hidden/);
  assert.match(html, /class="commander-name">ELISE<\/strong>/);
  assert.match(html, /src="\.\/assets\/character\/char1\.webp"/);
  assert.match(html, /id="panel-unit-count"/);
  assert.match(html, /id="panel-unit-count">24<\/span>\s*\/ 24/);
  assert.match(html, /id="panel-strength"/);
  assert.match(html, /id="panel-status"/);
  assert.match(html, /id="battle-result"[^>]*hidden/);
  assert.match(html, /id="result-title"/);
  assert.match(html, /id="result-restart"[^>]*>RESTART BATTLE<\/button>/);
  assert.match(html, /id="start-screen"/);
  assert.match(html, /id="start-title">EISENHERZ<\/h2>/);
  assert.match(html, /id="start-battle"[^>]*>START BATTLE<\/button>/);
  assert.match(html, /id="show-controls"[^>]*>CONTROLS<\/button>/);
  assert.match(html, /id="controls-dialog"[\s\S]*role="dialog"/);
  assert.match(html, /id="close-controls"[^>]*>CLOSE<\/button>/);
  assert.doesNotMatch(html, /CLICK \/ ENTER \/ SPACE TO START/);
  assert.doesNotMatch(html, /class="start-controls"/);
  assert.doesNotMatch(app, /startScreen\.addEventListener\("pointerup"/);
  assert.match(css, /button\.is-active\s*\{[^}]*background:\s*var\(--white\)/s);
  assert.match(css, /--cursor-default:\s*url\("\.\/assets\/icon\/mouse\.png"\) 0 0, auto;/);
  assert.match(css, /\*\s*\{[^}]*cursor:\s*var\(--cursor-default\)/s);
  assert.doesNotMatch(css, /cursor:\s*pointer/);
  assert.match(css, /\.battle-result\s*\{[^}]*border:\s*4px solid var\(--white\)/s);
  assert.match(css, /#result-restart\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(css, /body\s*\{[^}]*position:\s*fixed;[^}]*inset:\s*0;/s);
  assert.match(css, /\.game-shell\s*\{[^}]*height:\s*var\(--app-height, 100dvh\);[^}]*overflow:\s*hidden/s);
  assert.match(css, /\.loading\s*\{[^}]*position:\s*fixed;[^}]*z-index:\s*30;[^}]*background:\s*var\(--black\)/s);
  assert.match(css, /\.loading-card\s*\{[^}]*border:\s*4px solid var\(--white\)/s);
  assert.match(css, /\.loading i\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(css, /\.start-screen\s*\{[^}]*position:\s*fixed;[^}]*background:\s*var\(--black\)/s);
  assert.match(css, /#start-battle\s*\{[^}]*background:\s*var\(--red\)/s);
  assert.match(css, /\.controls-dialog\s*\{[^}]*border:\s*4px solid var\(--white\)/s);
  assert.match(css, /\.commander-panel\s*\{[^}]*width:\s*min\(320px, calc\(100vw - 28px\)\);[^}]*border:\s*3px solid var\(--white\)/s);
  assert.doesNotMatch(css, /cursor:\s*move/);
  assert.doesNotMatch(css, /cursor:\s*grabbing/);
  assert.match(css, /\.command-mode-buttons,\s*\.formation-mode-buttons\s*\{[^}]*grid-template-columns:\s*1fr 1fr/s);
  assert.match(css, /\.unit-status-panel\s*\{[^}]*top:\s*14px;[^}]*right:\s*14px;[^}]*width:\s*min\(390px, calc\(100vw - 28px\)\)/s);
  assert.match(css, /\.formation-units\s*\{[^}]*overflow-x:\s*auto/s);
  assert.match(css, /\.unit-card\.is-selected\s*\{[^}]*border-color:\s*var\(--red\)/s);
  assert.match(css, /\.selection-box\s*\{[^}]*border:\s*2px solid var\(--white\)/s);
  assert.match(css, /\.panel-selection-box\s*\{[^}]*border:\s*2px solid var\(--red\)/s);
  assert.match(css, /\.battle-status\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) 148px minmax\(0, 1fr\)/s);
  assert.match(css, /\.battle-status\s*\{[^}]*width:\s*372px;[^}]*min-width:\s*372px;[^}]*max-width:\s*372px/s);
  assert.match(css, /#battle-message\s*\{[^}]*width:\s*100%;[^}]*max-width:\s*148px/s);
  assert.match(app, /\["Enter", "Space"\]\.includes\(event\.code\)/);
  assert.match(app, /if \(!controlsDialog\.hidden\)/);
  assert.match(app, /event\.code === "Escape"/);
  assert.match(app, /window\.visualViewport\?\.addEventListener\("resize", syncViewportSize\)/);
  assert.match(app, /const loadingMessage = document\.getElementById\("loading-message"\)/);
  assert.match(app, /loadingMessage\.textContent = `起動エラー: \$\{error\.message\}`/);
  assert.match(app, /window\.addEventListener\("resize", syncViewportSize\)/);
  assert.match(app, /function syncViewportSize\(\)/);
  assert.match(app, /document\.documentElement\.style\.setProperty\("--app-height"/);
  assert.match(app, /window\.addEventListener\("click", blurClickedButton\)/);
  assert.match(app, /function blurClickedButton\(event\)/);
  assert.match(app, /event\.target\.closest\?\.\("button"\)\?\.blur\(\)/);
  assert.match(app, /event\.code === "Space"[\s\S]*?event\.preventDefault\(\)/);
  assert.doesNotMatch(app, /event\.target\.matches\?\.\("input, textarea, select, button/);
  assert.match(app, /function buildFormationPanel\(\)/);
  assert.match(app, /function startMapSelection\(event\)/);
  assert.match(app, /function startPanelSelection\(event\)/);
  assert.match(app, /function startExternalPanelSelection\(event\)/);
  assert.match(app, /function startHudPanelDrag\(event\)/);
  assert.match(app, /if \(event\.target\.closest\?\.\("button"\)\) return;/);
  assert.match(app, /function placeHudPanel\(panel, clientLeft, clientTop\)/);
  assert.match(app, /function stopPanelDragFromControlButton\(event\)/);
  assert.match(app, /function setFormationStyle\(style\)/);
  assert.match(app, /function syncFormationStyleButton\(\)/);
  assert.match(app, /function drawActiveMoveGhosts\(\)/);
  assert.match(app, /drawMoveGhost\(destination\.x, destination\.y, destination\.role, "committed"\)/);
  assert.match(app, /ctx\.setLineDash\(isCommitted \? \[10, 8\] : \[\]\)/);
  assert.match(app, /ctx\.globalAlpha = isCommitted \? 0\.62 : 1/);
  assert.match(app, /canvas\.dataset\.moveCommands/);
  assert.match(app, /function startCommandDrag\(event\)/);
  assert.match(app, /function formationDestinations\(centerX, centerY, angle\)/);
  assert.match(app, /function squareFormationDestinations\(centerX, centerY, angle, forward, lateral, roleGroups\)/);
  assert.match(app, /function lineFormationDestinations\(centerX, centerY, angle, forward, lateral, roleGroups\)/);
  assert.match(app, /function centeredGridOffset\(column, row, columns, lateralSpacing, forwardSpacing\)/);
  assert.match(app, /canvas\.dataset\.formationStyle = debugState\.formationStyle/);
  assert.match(app, /canvas\.addEventListener\("contextmenu", event => event\.preventDefault\(\)\)/);
  assert.match(app, /setAllyControlMode\(state\.battle, "hold"\)/);
  assert.match(app, /issueMoveOrder\(state\.battle, destinations\)/);
  assert.match(app, /function unitCardsInClientBounds\(bounds\)/);
  assert.match(app, /function alliedUnitsInScreenBounds\(bounds\)/);
  assert.match(app, /function toggleSelectionBy\(predicate, additive = false\)/);
  assert.match(app, /function toggleUnitSelection\(ids, additive = false\)/);
  assert.match(app, /if \(!additive && isEntireGroupSelected\(nextIds\)\)/);
  assert.match(app, /ctx\.rotate\(Math\.atan2\(dy, dx\) \+ Math\.PI\)/);
  assert.match(app, /canvas\.dataset\.selectedCount/);
  assert.match(app, /if \(!state\.started\) \{\s*if \(event\.code === "Enter"\) \{\s*event\.preventDefault\(\);\s*startBattle\(\);/s);
  assert.match(app, /if \(state\.started && !state\.paused\) updateBattle/);
  assert.match(app, /pauseButton\.textContent = state\.paused \? "RESUME" : "PAUSE"/);
  assert.match(app, /function initialCameraScale\(\) \{\s*return CAMERA_LIMITS\.minScale;/s);
});
